baseurl = "https://satoshun.github.io"
languageCode = "ja"
title = "stsn„Éñ„É≠„Ç∞"
theme = "hyde"
copyright = "Sato Shun"
publishDir = "../"

[Author]
	name = "Sato Shun"
	bio = "„ÅÇ„Çì„Å©„Çç„ÅÑ„Å©„Åß„ÅÉ„Åπ„Çç„Å£„Å±„ÅÅ„Éºüçé"

[Permalinks]
	blog = "/:year/:month/:filename/"
	book = "/:year/:month/:filename/"
	hobby = "/:year/:month/:filename/"
	gallery = "/:year/:month/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Android, Python, Reactive, DB(RDS), Engineer"
	twitter = "https://twitter.com/stsn_jp"
	github = "https://github.com/satoshun"
	gplus = "https://plus.google.com/102988556020375542271"
	icon = "https://goo.gl/tVvkdT"
